### ISSUE TITLE
Does not reset timer when user interacts with page

### ISSUE THREAD

**Issue by jersingh** [travishorn/session-timeout#1]
After installation, I can click buttons and move the mouse around and the dialog will appear regardless.

My config:

sessionTimeout({
        warnAfter: 5000,
        message: 'Are you still there?',
        keepAliveUrl: '/keep-alive',
        logOutUrl: '/logout',
        keepAliveMethod: 'GET'
});

**Comment by travishorn** [comment]
Typically, actions like HTTP requests reset the timeout for a session on most servers. Moving the mouse or clicking buttons, however, don't.

I'm thinking it might be helpful to have some sort of manual reset method that you could call on this library when the user clicks on a button that you _know_ resets the session timeout.
