### ISSUE TITLE
Request for the unminified session-timeout.js

### ISSUE THREAD

**Issue by nabielm** [travishorn/session-timeout#15]
@travishorn can you upload the unminified version of the session-timeout.js? This will help a lot in understanding the code behind the scene.  

Btw, this is a wonderful script to notify session expiry and I highly appreciate the contributors' work for this script.

**Comment by travishorn** [comment]
The unminified version is split into two files: `src/index.css` and `src/index.js`. You can find them in this repository. During build, these two files are bundled using webpack and output to `dist/session-timeout.js`.
