### ISSUE TITLE
Does this project have an unminified version?

### ISSUE THREAD

**Issue by srs-srsly** [travishorn/session-timeout#2]
I need to modify this project to add a resetTimout function, but the src folder does not contain the unminified code. Is there any plan to add the unminified version?

**Comment by travishorn** [comment]
[The src directory](https://github.com/travishorn/session-timeout/tree/master/src) does indeed contain the unminified code. [index.css](https://github.com/travishorn/session-timeout/blob/master/src/index.css) contains the unminified CSS and [index.js](https://github.com/travishorn/session-timeout/blob/master/src/index.js) contains the unminified JavaScript.
