### ISSUE TITLE
The Options are wrong.

### ISSUE THREAD

**Issue by Sc0tsmanGB** [travishorn/session-timeout#44]
Your supplied Options are incorrect, it is not logOutUrl it is redirUrl, it is not titleText it is title, there are others also but I'm sure you get the idea.

**Comment by travishorn** [comment]
I'm not quite understanding your issue. Are you saying the documentation in the README is incorrect?

The README shows options such as `logOutUrl`, which you can see is the name of the option in the source code [here](https://github.com/travishorn/session-timeout/blob/master/src/index.js#L41). And `titleText` is the option used [here](https://github.com/travishorn/session-timeout/blob/master/src/index.js#L76).

You mentioned some options named `redirUrl` and `title` but neither of those options appear in the README or the source code.
