### ISSUE TITLE
Understanding keep-alive

### ISSUE THREAD

**Issue by tom11011** [travishorn/session-timeout#9]
Hello, I understand by default the script will call /keep-alive.

But I wasn't clear on if this file actually needs to exist and if so, does it need to be something like /keep-alive.php if using PHP.  In addition, does session_start() need to be on this page?  Anything else?

Thanks, plugin seems great for my needs.

Tom

**Comment by travishorn** [comment]
I think you are on the right track. I'm not familiar with PHP, but you should look up how PHP tracks active sessions and research a way to keep it active. Create a "dummy" page that performs that function, and then set session-timeout to hit that page with the `keepAliveUrl` option.
